"""initial_schema_with_indexes

Revision ID: 3428989358d4
Revises: 
Create Date: 2025-10-20 13:55:01.917960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3428989358d4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('signatures', sa.Column('pdf_hash_cached', sa.String(length=64), nullable=True))
    op.add_column('signatures', sa.Column('pdf_file_path', sa.String(length=500), nullable=True))
    op.create_index('idx_signatures_file_id', 'signatures', ['file_id'], unique=False)
    op.create_index('idx_signatures_hash', 'signatures', ['signature_hash'], unique=False)
    op.create_index('idx_signatures_status', 'signatures', ['status'], unique=False)
    op.create_index('idx_signatures_timestamp', 'signatures', ['timestamp'], unique=False)
    op.create_index('idx_signatures_user_id', 'signatures', ['user_id'], unique=False)
    op.create_index(op.f('ix_signatures_pdf_hash_cached'), 'signatures', ['pdf_hash_cached'], unique=False)
    op.create_index('idx_sessions_expires_at', 'user_sessions', ['expires_at'], unique=False)
    op.create_index('idx_sessions_session_id', 'user_sessions', ['session_id'], unique=False)
    op.create_index('idx_sessions_user_id', 'user_sessions', ['user_id'], unique=False)
    op.create_index('idx_users_email', 'users', ['email'], unique=False)
    op.create_index('idx_users_role', 'users', ['role'], unique=False)
    op.create_index('idx_users_username', 'users', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_users_username', table_name='users')
    op.drop_index('idx_users_role', table_name='users')
    op.drop_index('idx_users_email', table_name='users')
    op.drop_index('idx_sessions_user_id', table_name='user_sessions')
    op.drop_index('idx_sessions_session_id', table_name='user_sessions')
    op.drop_index('idx_sessions_expires_at', table_name='user_sessions')
    op.drop_index(op.f('ix_signatures_pdf_hash_cached'), table_name='signatures')
    op.drop_index('idx_signatures_user_id', table_name='signatures')
    op.drop_index('idx_signatures_timestamp', table_name='signatures')
    op.drop_index('idx_signatures_status', table_name='signatures')
    op.drop_index('idx_signatures_hash', table_name='signatures')
    op.drop_index('idx_signatures_file_id', table_name='signatures')
    op.drop_column('signatures', 'pdf_file_path')
    op.drop_column('signatures', 'pdf_hash_cached')
    # ### end Alembic commands ###
